name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          python3 -m pytest test/

          # Set the status of the build based on the test results
          if [ $? -ne 0 ]; then
            exit 1
          fi
