name: Tests

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python 3
        run: |
          sudo apt-get update
          sudo apt-get install python3
      - name: Install pip3
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip
      - name: Install pytest
        run: |
          pip3 install pytest

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pre-build
      - name: Run tests
        run: |
          python3 -m pytest test/

          # Set the status of the build based on the test results
          if [ $? -ne 0 ]; then
            exit 1
          fi
