name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pre-build
        run: |
          sudo apt-get update
          sudo apt-get install python3
          sudo apt-get update
          sudo apt-get install python3-pip
          pip3 install pytest
      - name: tests
        run: |
          python3 -m pytest test/

          if [ $? -ne 0 ]; then
            exit 1
          fi
